example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import (
    register,
    show_todolist,
    login_user,
    logout_user,
    create_task,
    delete_task,
    update_task,
    add_task_json,
    delete_task_json,
    show_task_json,

)

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path("delete/<int:post_id>", delete_task, name="delete_task"),
    path("delete/json/<int:post_id>", delete_task_json, name="delete_task_json"),
    path("update/<int:post_id>", update_task, name="update_task"),
    path("json", show_task_json, name="show_task_json"),
    path("create/json", add_task_json),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField() 

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyFilm(models.Model):
    watched = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=50)
    review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length = 255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):
    list_item = CatalogItem.objects.all()
    context = {
    'list_item': list_item,
    'nama' : 'Alifia',
    'NPM': '2106634723'
}
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyFilm
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    my_watch_list = MyFilm.objects.all()
    context = {
        'watch_list' : my_watch_list,
        'nama' : 'Alifiaa',
        'NPM' : '2106634723'
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    my_watch_list = MyFilm.objects.all()
    return HttpResponse(serializers.serialize("xml", my_watch_list), content_type="application/xml")

def show_json(request):
    my_watch_list = MyFilm.objects.all()
    return HttpResponse(serializers.serialize("json", my_watch_list), content_type="application/json")

todolist/views.py
import datetime
from django import forms
from todolist.models import Task
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.core import serializers
from django.urls import reverse
from datetime import date

class NewTodoForm(forms.Form):
    date = forms.DateField(label="Tanggal")
    title = forms.CharField(label="Judul")
    description = forms.CharField(
        label="Deskripsi", widget=forms.Textarea(attrs={"cols": ""})
    )

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todo_list = Task.objects.filter(user = request.user)
    user = request.user
    context = {
        'list_todo': todo_list,
        'username' : user,
    }
    return render(request, "todolist.html", context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
           login(request, user) # melakukan login terlebih dahulu
           return redirect("todolist:show_todolist")
        else:
            messages.info(request, 'Wrong Username or Password!')
    return render(request, 'login.html')

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account has been created successfully!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login_user'))
    return response

def create_task(request):
    if request.method == "POST":
        form = Form(request.POST)
        
        new_task = Task()
        new_task.user = request.user
        new_task.date = datetime.date.today()
        new_task.task_name = form.data['task_name']
        new_task.description = form.data['description']
        new_task.save()
        
        response = HttpResponseRedirect(reverse("todolist:show_todolist"))
        messages.success(request, 'Task saved.')
        return(response)
    else:
        context = {}
        return render(request, 'create_task.html', context)

def update_task(request, post_id: int):
    if request.method == "POST":
        task = Task.objects.filter(id=post_id, user=request.user).first()
        if task:
            task.is_finished = not task.is_finished
            task.save()
            messages.success(request, "Successful update!")
        else:
            messages.error(request, "Tasks not found!")

    return redirect("todolist:show_todolist")

def delete_task(request, post_id: int):
    if request.method == "POST":
        task = Task.objects.filter(id=post_id, user=request.user).first()
        if task:
            task.delete()
            messages.success(request, "Successfully deleted!")
        else:
            messages.error(request, "Tasks not found!")

    return redirect("todolist:show_todolist")

@login_required(login_url="/todolist/login")
def show_task_json(request: HttpRequest):
    todos = Task.objects.filter(user=request.user).order_by("date").all()
    return HttpResponse(
        serializers.serialize("json", todos), content_type="application/json"
    )


@login_required(login_url="/todolist/login")
def add_task_json(request: HttpRequest):
    if request.method == "POST":
        task = Task(
            date=date.fromisoformat(request.POST["date"]),
            title=request.POST["title"],
            description=request.POST["description"],
            user=request.user,
        )
        task.save()
        return HttpResponse(
            serializers.serialize("json", [task]),
            content_type="application/json",
        )
    return HttpResponse("Invalid method", status_code=405)


@login_required(login_url="/todolist/login")
def delete_task_json(request: HttpRequest, post_id: int):
    if request.method == "DELETE":
        task = Task.objects.filter(id=post_id, user=request.user).first()
        if task:
            task.delete()
            return HttpResponse("OK")
        else:
            return HttpResponse("Not Found", status_code=404)

    return HttpResponse("Invalid method", status_code=405)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{NPM}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_item %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{NPM}}</p>

  <table>
    <tr>
      <th>watched</th>
      <th>title</th>
      <th>rating</th>
      <th>release_date</th>
      <th>review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in watch_list %}
    <tr>
        <th>{{film.watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/daisyui@2.31.0/dist/full.css" rel="stylesheet" type="text/css" />
  <script src="https://cdn.tailwindcss.com"></script>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;700&display=swap" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  {% block meta %}
  {% endblock meta %}
</head>

<body class="bg-base-200 w-full min-h-screen">
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %} {% block meta %}
{% load static %}
<title>Create your new task</title>
<body style="background-color: #23242a;">
{% endblock meta %} {% block content %}

<div class="container">
	<form method="POST" action="{% url 'todolist:create_task' %}">
		{% csrf_token %}
		<div style="display: flex; flex-direction: column; gap: 24px">
			<h1 style="font-size: 3rem; color: #f94fd7e6; font-family: Lucida Bright; display: flex; align-items: center; justify-content: center;">Create your task</h1>
			<div style="display: flex; flex-direction: column; gap: 8px">
				<div style="display: flex; flex-direction: column; gap: 4px">
					<div style="font-size: 2rem; color: #f94fd7e6; font-family: Lucida Bright;">Title</div>
					<input
						type="text"
						name="title"
						placeholder="Title"
						class="form-control"
						required
					/>
				</div>
				<div style="display: flex; flex-direction: column; gap: 4px">
					<div style="font-size: 2rem; color: #f94fd7e6; font-family: Lucida Bright;">Description:</div>
					<textarea
						name="description"
						rows="5"
						placeholder="Description"
						class="form-control"
					></textarea>
				</div>
			</div>
			<input class="btn btn-primary" type="submit" value="Create Task" />
		</div>
	</form>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}
{% block meta %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel= "stylesheet" href="{% static 'style.css' %}">
    {% endblock meta %}
    {% block content %}
</head>
<body>
    <div class = "box">
        <div class = "form">
            <h2>Sign in</h2>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="inputBox"> 
                    <input type="text" required="required" class="form-control">
                    <span>Username</span>
                    <i></i>
                </div>
                <div class="inputBox"> 
                    <input type="password" required="required" class="form-control">
                    <span>Password</span>
                    <i></i>
                </div>
                <div class="links">
                    not have account?
                    <a href="{% url 'todolist:register' %}">Create Account</a>
                </div>
                <input class="btn btn-primary login_btn" type="submit" value="Login" />
            </form>
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
</body>
</html>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}
{% block meta %}
{% load static %}
<link rel= "stylesheet" href="{% static 'register.css' %}">
<body style="background-color: #c247a9e6;"></body>
{% endblock meta %}

<title>Account Registration</title>

{% block content %}  

<div class = "login">
    
    <h1>Registration Form</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>TODO List</title>
{% endblock meta %}

{% block content %}

<style>
  input, textarea {
   padding: 0.5rem;
   border: 1px solid;
   border-radius: 8px;
   width: 100%
  }
</style>

<div class="container mx-auto pt-4 flex flex-col gap-4">
  <div class="flex flex-row items-center justify-center md:justify-end gap-4">
    <p class="text-xl">
      Halo, {{ user.get_username }}
    </p>
    <a href="{% url 'todolist:logout_user' %}" class="btn btn-error ">Keluar</a>
    <label for="my-modal" class="btn btn-primary">Buat baru</a>
  </div>

  {% if messages %}
  <ul class="alert alert-info flex-col text-left text-info-content">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

  <div id="todosContainer" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
  </div>

  <input type="checkbox" id="my-modal" class="modal-toggle" />
  <label for="my-modal" class="modal cursor-pointer">
    <label for="" class="modal-box relative">
      <form id="newForm" class="flex flex-col gap-4">
        {% csrf_token %}
        <div class="form-control w-full max-w-md">
            <label for="id_date">Tanggal:</label>
            <input type="text" name="date" required="" id="id_date">
        </div>
    
        <div class="form-control w-full max-w-md">
            <label for="id_title">Judul:</label>
            <input type="text" name="title" required="" id="id_title">
        </div>
    
        <div class="form-control w-full max-w-md">
            <label for="id_description">Deskripsi:</label>
            <textarea name="description" cols="" rows="10" required="" id="id_description"></textarea>
        </div>


        <div class="flex flex-col md:flex-row gap-2 w-full">
          <label for="my-modal" class="btn">Batal</label>
          <button class="btn btn-primary" id="newBtn">Buat</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  let container;
  function createCardHtml(todo, id) {
    const { title, date, description} = todo
    const isFinishedText = todo.is_finished ? "Finished" : "Not Finished"
    return `
      <div class="scale-100 hover:scale-105 transition card bg-neutral text-neutral-content">
        <div class="card-body items-center text-center">
          <h2 class="card-title">${title}</h2>
          <span>${date} | ${isFinishedText}</span>
          <p class="break-all">${description}</p>
          <div class="card-actions justify-end">
            <form action="/todolist/update/${id}" method="POST">
              {% csrf_token %}
              <button class="btn btn-primary">Toggle</button>
            </form>
            <form action="/todolist/delete/${id}" method="POST">
              {% csrf_token %}
              <button class="btn btn-error removebtn" data-id="${id}">Delete</button>
            </form>
          </div>
        </div>
      </div>
    `
  }

  function removeTodo(e) {
    const id = $(e.target).data("id")
    e.preventDefault()
    $.ajax({
      type: 'DELETE',
      url: '/todolist/delete/json/' + id,
      beforeSend: function(xhr) {
        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
      },
      success: () => {
        alert("Done!")
        fetchData()
      }
    })
  }

  function renderTodo(todos) {
    todos.map((todo) => {
      const newNode = $(createCardHtml(todo.fields, todo.pk))
      newNode.find(".removebtn").click(removeTodo)
      container.append(newNode)
    })
  }

  function fetchData() {
    container.empty()
    $.get("{% url 'todolist:show_todos_json' %}", renderTodo)
  }

  function createTodo(e) {
    e.preventDefault()
     $.ajax({
      type: 'POST',
      url: '/todolist/create/json',
      data: $("#newForm").serialize(), 
      success: () => {
        alert("Done!")
        $("#my-modal").click()
        fetchData()
      },
      dataType: 'json'
    });
  }

  $(document).ready(() => {
    $("#newBtn").click(createTodo)
    container = $("#todosContainer")
    fetchData()
  })


</script>
{% endblock content %}